sources:
  - name: main
    tables:
      - name: raw_admissions
      - name: raw_diagnoses_icd
      - name: raw_prescriptions
      - name: raw_procedures_icd
      - name: raw_labevents
      - name: raw_emar
      - name: top_200_labs
      - name: lab_quantiles
      - name: drug_to_atc
      - name: icd_cm_9_to_10
      - name: icd_pcs_9_to_10

