name: hat
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pytorch::pytorch>=2.0.0
  - pytorch::torchvision>=0.15
  - pytorch::torchaudio>=2.0
  - nvidia::pytorch-cuda=12.1
  - numpy>=1.24.0
  - pip
  - pip:
      - tqdm>=4.65.0
      - pandas>=2.0.0
      - pyarrow>=12.0.0
      - duckdb>=0.9.0
      - tokenizers>=0.15.0
      - mlflow>=2.8.0
      - transformers>=4.30.0
