name: 'nbr'
version: '1.0.0'

profile: 'nbr'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nbr:
    stg:
      +materialized: view
    curated:
      +materialized: table

